closecommenting/urls.py
from django.conf.urls.defaults import *
import views as text_views
from closecommenting.feeds import LatestEntries

# TODO:
# Propose raw formats (markdown and plain text) 
urlpatterns = patterns('',
    url(r'^(?P<slug>[-\w]+).html$', view=text_views.text_detail, name='closecommenting-detail'),
    url(r'^(?P<slug>[-\w]+).mdx$', view=text_views.text_detail, name='closecommenting-mdx'),
    url(r'^feeds/comments$', view=text_views.rss, name='closecommenting-rss'),
)

feeds = {
    'latest': LatestEntries, 
}

urlpatterns += patterns('django.contrib.syndication.views',
    (r'^feeds/(?P<url>.*)/$', 'feed', {'feed_dict': feeds}),
)

closecommenting/models.py
# *-* encoding: utf-8 *-*

## Copyright 2010 Stéphanie Vilayphiou, Alexandre Leray

## This file is part of Close Commenting.
## 
## Close Commenting is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## any later version.
## 
## Close Commenting is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Close Commenting.  If not, see <http://www.gnu.org/licenses/>.


from django.db import models
from django.utils.translation import ugettext_lazy as _
from dcdocuments.models import Document

from textwrap import dedent

import hashlib, re, markdown
from BeautifulSoup import BeautifulSoup


class Text(Document):
    """
    Describes a text document.
    """
    
    body = models.TextField(verbose_name=_('Body'), default=dedent("""\
        contributor: [ex: "Reinfurt"]
        coverage:    [ex: "Berlin, Germany"]
        creator:     [ex: "David Reinfurt"]
                     [ex: "Alexandre Leray"]
        date:        [ex: "01/01/2002"]
        description: [ex: "David Reinfurt explains some things"]
        format:      [ex: "text/markdown"]
        identifier:  [ex: "one-possible-scenario-for-a-collective-future"]
        language:    [ex: "English"]
        publisher:   [ex: "Dot Dot Dot"]
        relation:    [ex: "Dot Dot Dot 6"]
        rights:      [ex: "Copyright David Reinfurt"]
        source:      [ex: "Issue Magazine"]
        subject:     [ex: "Open Source"]
                     [ex: "Graphic Design"]
        title:       [ex: "One Possible Scenario for a Collective Future"]
        type:        [ex: "Essay"]
        
        """)
    )
    body_html = models.TextField(null=True, blank=True)
        
    def save(self):
        """
        Saves the text and split it in pieces according to its paragraphs breaks.
        Compare the new paragraphs checksums with the existing ones, if any.
        Matching checksum paragraphs are preserved, allowing consistency in comment linking.
        Non-Matching checksum paragraphs are deleted.
        """
        
        ## TODO: check if we can get rid of the save() redundency
        super(Text, self).save()
        
        ## TODO: check Difflib and see how it could be integrated
        
        # Retrieves existing paragraphs
        existing_paragraphs = Paragraph.objects.filter(text=self)
        # Converts markdown to HTML
        md = markdown.Markdown(extensions=['meta', 'footnotes', 'def_list'])
        output = md.convert(self.body)
        # cache the html
        self.body_html = output

        # Populates the metadata
        self.dc_contributor = md.Meta.get('contributor', [''])[0]
        self.dc_coverage    = md.Meta.get('coverage', [''])[0]
        self.dc_creator     = md.Meta.get('creator', [''])[0]
        self.dc_date        = md.Meta.get('date', [''])[0]
        self.dc_description = md.Meta.get('description', [''])[0]
        self.dc_format      = md.Meta.get('format', [''])[0]
        self.dc_identifier  = md.Meta.get('identifier', [''])[0]
        self.dc_language    = md.Meta.get('language', [''])[0]
        self.dc_publisher   = md.Meta.get('publisher', [''])[0]
        self.dc_relation    = md.Meta.get('relation', [''])[0]
        self.dc_rights      = md.Meta.get('rights', [''])[0]
        self.dc_source      = md.Meta.get('source', [''])[0]
        self.dc_subject     = md.Meta.get('subject', [''])[0]
        self.dc_title       = md.Meta.get('title', [''])[0]
        self.dc_type        = md.Meta.get('type', [''])[0]
        
        super(Text, self).save()
        
        # Creates a list of tuples (paragraph_content , checksum)
        new_paragraphs = [] 
        
        # Iterates through each first level node
        for p in BeautifulSoup(output):
            # print p
            # Excludes empty text nodes
            if not unicode(p.string).encode('utf-8').isspace():
                # Encode the node content and computes its md5 hash
                text = unicode(p).encode('utf-8')
                checksum = hashlib.sha1(text)
                new_paragraphs.append((text, checksum.hexdigest()))
        
        # Creates a set of the new paragraphs checksums
        new_checksums = set(t[1] for t in new_paragraphs)
        # Deletes removed paragraphs
        for p in existing_paragraphs:
            if not p.checksum in new_checksums:
                p.delete()
        
        # Creates a set of the existing paragraphs checksums
        existing_checksums = set(p.checksum for p in existing_paragraphs)
        i = 0
        for p, cs in new_paragraphs:
            if cs in existing_checksums:
                # update existing paragaraph order
                paragraph = existing_paragraphs.get(checksum=cs)
                paragraph.order = i
                paragraph.save()
            else:
                paragraph = Paragraph()
                paragraph.text = self
                paragraph.content = p
                paragraph.checksum = cs
                paragraph.order = i
                paragraph.save()
            i += 1
    
    @models.permalink
    def get_absolute_url(self):
        return ('closecommenting-detail', (), {'slug': self.dc_identifier,})
    class Meta:
        ordering = ['dc_title']


# TODO:
# Rename this class "Chunck" (or "section"?)
class Paragraph(models.Model):
    """
    Describes a paragraphs to comment on. Automatically created 
    after a Text when the paragraph comment option is checked.
    """
    
    text     = models.ForeignKey(Text)
    content  = models.TextField()
    checksum = models.CharField(max_length=32)
    order    = models.IntegerField(blank=True, null=True)
    
    def __unicode__(self):
        return u'%s' % self.content[0:100]
    
    class Meta:
        ordering = ('order',)

closecommenting/templates/comments.html
{% load comments %}
{% load threadedcomments_tags %}
{% load markup %}
{% load url_utils %}
{% load utils %}


{% for comment in comment_list|fill_tree|annotate_tree %}

    {% ifchanged comment.parent_id %}{% else %}
        </li>
    {% endifchanged %}

    {% if not comment.open and not comment.close %}
        </li>
    {% endif %}

    {% if comment.open %}
        <ul>
    {% endif %}

    <li{% if comment.last %} class="last"{% endif %}>
    
    <div id="comment_{{ comment.id }}">
        {{ comment.comment|markdown }}                            
    </div>
    
    <div class="signature">
        {% ifnotequal comment.user_url "" %}
            by <a href="{{ comment.user_url }}">{{ comment.user_name }}</a>, 
            {{ comment.submit_date|timesince }} ago
        {% else %}
            by {{ comment.user_name }}, {{ comment.submit_date|timesince }} ago
        {% endifnotequal %}
        | <a href='{% query_string "" "cc, cp, ct" %}cc={{ comment.id }}#add-comment'>reply</a>&nbsp;↩
    </div>
    
    {% ifequal comment.id cc %}
    
        {% get_comment_form for comment_target as comment_form with comment.id %}
        {% assign comment_on comment.comment %}
        {% include 'comment-form.html' %}
    
    {% endifequal %}

    {% for close in comment.close %}
        </li>
        </ul>
    {% endfor %}

{% endfor %}

closecommenting/templates/text.html
{% extends 'base.html' %}

{% load comments %}
{% load threadedcomments_tags %}
{% load markup %}
{% load url_utils %}
{% load utils %}


{% block title %}
    {{ text.dc_title }} 
    by 
    {% for creator in text.dc_creator.all %}
        {{ creator }}
    {% endfor %}
{% endblock title %}


{% block content %}
    
    <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        var elt = $("#metadata dl:first");
        elt.hide();
        $("#metadata p:first").click(function () {
            elt.is(":hidden") ? elt.slideDown('fast') : elt.slideUp('fast');
        });
    });
    </script>
    
    <div id="page">
        
        <div id="metadata">
            <div class="content">
                <p>Document metadata (↓View/Hide)</p>
                <dl>
                    <dt>Author{{ text.dc_creator.all|pluralize }}</dt>
                    {% for creator in text.dc_creator.all %}
                        <dd>{{ creator }}</dd>
                    {% endfor %}
                    <dt>Publishing Date</dt>
                        <dd>{{ text.dc_date }}</dd>
                    <dt>Language</dt>
                        <dd>{{ text.dc_language }}</dd>
                </dl>
            </div>
        </div>
        
        <table id="text-table">
            <colgroup>
                <col id="col-paragraphs" />
                <col id="col-comments" />
            </colgroup>
                <tr>
                    <td>
                        <h1>{{ text.dc_title }}</h1>
                    </td>
                    <td></td>
                </tr>
            {% for paragraph in text.paragraph_set.all %}
                <tr>
                    <td>{{ paragraph.content|safe}}</td>
                    <td>
                        {% get_comment_count for paragraph as comment_count %}
                        <div class="comment-count">
                            <a href='{% query_string "" "cc, cp, ct" %}cp={{ paragraph.id }}#add-comment'>✎ {{ comment_count }}</a>                            
                        </div>
                        
                        {% get_comment_list for paragraph as comment_list %}
                        {% assign comment_target paragraph %}
                        {% include 'comments.html' %}
                        
                        {% ifequal cp paragraph.id  %}
                            {% get_comment_form for paragraph as comment_form %}
                            {% assign comment_on paragraph.content %}
                            {% include 'comment-form.html' %}
                        {% endifequal %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div id="general-comments">
            <div class="content">
                
                {% get_comment_count for text as comment_count %}
                <div id="general-comment-count">
                    <a href='{% query_string "" "cc, cp, ct" %}ct={{ text.id }}#add-comment'>
                        ✎ {{ comment_count }} general comment{{ comment_count|pluralize }}
                    </a>
                </div>
                
                {% get_comment_list for text as comment_list %}
                {% assign comment_target text %}
                {% include 'comments.html' %}
                
                {% ifequal ct text.id  %}
                    {% get_comment_form for text as comment_form %}
                    {% assign comment_on text.body %}
                    {% include 'comment-form.html' %}
                {% endifequal %}
                
            </div>
        </div>
        
    </div>
    
{% endblock content %}